#!/bin/bash
alias ls='ls --color=auto'
alias ll='eza -la'
alias ls='eza'
alias vi='nvim'
alias vim='nvim'
alias grep='grep --color=auto --ignore-case'
alias serve='python3 -m http.server'
if [ -f "/opt/homebrew/bin/brew" ]; then
  true
else
  alias open='xdg-open'
fi
alias dotnet='TERM=xterm dotnet'
alias func="TERM=xterm func"
alias pwsh="TERM=xterm pwsh"
alias cat='bat'

if command -v batcat &>/dev/null; then
  alias bat='batcat'
fi

alias ping='prettyping --nolegend'
alias help='tldr'
alias df='pydf'

# alias less='less -R'
alias vim="nvim"
alias ftp='lftp'
alias dmesg='dmesg -H'
# Makes xclip work with vim
alias xclip='xclip -selection c'

alias dotdrop='$DOTREPO/dotdrop.sh'
alias dotgit='git -C $DOTREPO'
alias dotsync="dotgit pull && dotgit add -A && dotgit commit && dotgit push; dotdrop install"
alias fclear='tput reset'

alias minikubectl="minikube kubectl --"
function jsonv() {
  file=$1
  jq --color-output '.' "$file" | cat -p
}

function man-http() {
  code="$1"
  if [[ -z $code ]]; then
    echo "Usage: man-http <status code>"
    exit 0
  fi

  xdg-open "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/$code"
}

function iterate-dates() {
  currentDateTs=$(date -j -f "%Y-%m-%d" "$1" "+%s")
  endDateTs=$(date -j -f "%Y-%m-%d" "$2" "+%s")
  offset=86400
  DATES=()

  while [ "$currentDateTs" -le "$endDateTs" ]; do
    date=$(date -j -f "%s" "$currentDateTs" "+%Y-%m-%d")
    echo "$date"
    DATES+=("$date")
    currentDateTs=$(($currentDateTs + $offset))
  done

}

alias clj-repl="clojure -M:repl/rebel"
alias cljs-repl="clojure -M:repl/cljs"

function absorbpre() {
  FS=$(git diff --cached --name-status | cut -f2 | tr '\n' ' ')
  pre-commit run --files "${FS}" && git absorb --and-rebase
}

alias urldecode="python -c 'import sys, urllib.parse as ul; print(ul.unquote_plus(sys.argv[1]))'"
