#!/bin/bash
alias ls='ls --color=auto'
alias ll='exa -la'
alias ls='exa'
alias vi='nvim'
alias grep='grep --color=auto --ignore-case'
alias serve='python3 -m http.server'
alias open='xdg-open'
alias dotnet='TERM=xterm dotnet'
alias func="TERM=xterm func"
alias pwsh="TERM=xterm pwsh"
alias cat='bat'

if command -v batcat &>/dev/null; then
	alias bat='batcat'
fi

alias ping='prettyping --nolegend'
alias help='tldr'
alias df='pydf'
alias pacman='pacman --color=always'
# alias less='less -R'
alias vim="nvim"
alias ftp='lftp'
alias dmesg='dmesg -H'
# Makes xclip work with vim
alias xclip='xclip -selection c'
alias cwt='cw tail --group-name --stream-name --start=1m --local --follow'

# Your dotdrop git repository location
export DOTREPO="$HOME/dotfiles"

alias dotdrop='$DOTREPO/dotdrop.sh'
alias dotgit='git -C $DOTREPO'
alias dotsync="dotgit pull && dotgit add -A && dotgit commit && dotgit push; dotdrop install"

alias cljfmt="lein cljfmt"
alias cljrepl="clj -M:nREPL -m nrepl.cmdline"

alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'

alias norg="gron --ungron"
alias ungron="gron --ungron"
alias voiceflow="voiceflow.AppImage"
alias istoolbx='[ -f "/run/.toolboxenv" ] && grep -oP "(?<=name=\")[^\";]+" /run/.containerenv'

alias cdk1="npx aws-cdk@1.x"
alias cdk="npx aws-cdk@2.x"
alias aws_cf_stacks='aws cloudformation list-stacks --output table --query "StackSummaries[?StackStatus!=\`DELETE_COMPLETE\`].StackName"'

alias minikubectl="minikube kubectl --"
function jsonv() {
	file=$1
	jq --color-output '.' $1 | cat -p
}

function man-http() {
	code="$1"
	if [[ -z $code ]]; then
		echo "Usage: man-http <status code>"
		exit 0
	fi

	xdg-open "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/$code"
}
alias jq="gojq"
