#!/bin/bash
#
# ~/.bash_profile
#
# shellcheck disable=SC1090

[[ -f ~/.profile ]] && . ~/.profile
[[ -f ~/.bashrc ]] && . ~/.bashrc

if [ -n "$DESKTOP_SESSION" ]; then
	eval "$(gnome-keyring-daemon --start)"
	export SSH_AUTH_SOCK
fi

export QT_AUTO_SCREEN_SCALE_FACTOR=1

[ -s "/home/armonge/.jabba/jabba.sh" ] && source "/home/armonge/.jabba/jabba.sh"

export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.poetry/bin:$PATH"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
export PATH="/home/armonge/.ebcli-virtual-env/executables:$PATH"
