actions:
  post:
    dein: vim --cmd ':call dein#recache_runtimepath()'
    dein_install: cd ~/.cofig/nvim/ && ./installer.sh
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_by_default: true
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_bashrc:
    dst: ~/.bashrc
    link: !!python/object/apply:dotdrop.linktypes.LinkTypes
    - 1
    src: bashrc
  f_gitconfig:
    dst: ~/.gitconfig
    link: !!python/object/apply:dotdrop.linktypes.LinkTypes
    - 1
    src: gitconfig
  f_init.vim:
    actions:
    - dein
    dst: ~/.config/nvim/init.vim
    link: !!python/object/apply:dotdrop.linktypes.LinkTypes
    - 1
    src: config/nvim/init.vim
  f_installer.sh:
    actions:
    - dein_install
    dst: ~/.config/nvim/installer.sh
    link: !!python/object/apply:dotdrop.linktypes.LinkTypes
    - 1
    src: config/nvim/installer.sh
profiles:
  armonge-laptop:
    dotfiles:
    - f_bashrc
    - f_init.vim
    - f_installer.sh
    - f_gitconfig
