config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: link
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_asus_zenbook3_deluxe_auo_b140han03_8.icm:
    dst: ~/.local/share/icc/Asus_Zenbook3_Deluxe_AUO_B140HAN03_8.icm
    link: link
    src: local/share/icc/Asus_Zenbook3_Deluxe_AUO_B140HAN03_8.icm
  f_bash_aliases:
    dst: ~/.bash_aliases
    link: link
    src: bash_aliases
  f_bash_profile:
    dst: ~/.bash_profile
    link: link
    src: bash_profile
  f_bashrc:
    dst: ~/.bashrc
    link: link
    src: bashrc
  f_chromium-flags.conf:
    dst: ~/.config/chromium-flags.conf
    link: link
    src: config/chromium-flags.conf
  f_ctags:
    dst: ~/.ctags
    link: link
    src: ctags
  f_gitconfig:
    dst: ~/.gitconfig
    link: link
    src: gitconfig
  f_init.vim:
    dst: ~/.config/nvim/init.vim
    link: link
    src: config/nvim/init.vim
  f_installer.sh:
    dst: ~/.config/nvim/installer.sh
    link: link
    src: config/nvim/installer.sh
  f_typescript.snippets:
    dst: ~/.config/nvim/UltiSnips/typescript.snippets
    link: link
    src: config/nvim/UltiSnips/typescript.snippets
  f_attributes:
    src: config/git/attributes
    dst: ~/.config/git/attributes
    link: link
  f_deps.edn:
    src: clojure/deps.edn
    dst: ~/.clojure/deps.edn
    link: link
  f_coc-settings.json:
    src: config/nvim/coc-settings.json
    dst: ~/.config/nvim/coc-settings.json
    link: link
  f_config.toml:
    src: config/pypoetry/config.toml
    dst: ~/.config/pypoetry/config.toml
    link: link
  f_ideavimrc:
    src: ideavimrc
    dst: ~/.ideavimrc
    link: link
  f_audio.vim:
    src: config/nvim/ftdetect/audio.vim
    dst: ~/.config/nvim/ftdetect/audio.vim
    link: link
  f_video.vim:
    src: config/nvim/ftdetect/video.vim
    dst: ~/.config/nvim/ftdetect/video.vim
    link: link
  f_ftplugin_audio.vim:
    src: config/nvim/after/ftplugin/audio.vim
    dst: ~/.config/nvim/after/ftplugin/audio.vim
    link: link
  f_ftplugin_video.vim:
    src: config/nvim/after/ftplugin/video.vim
    dst: ~/.config/nvim/after/ftplugin/video.vim
    link: link
  f_dircolors:
    src: dir_colors/dircolors
    dst: ~/.dir_colors/dircolors
    link: link
  f_colorize_terminal.sh:
    src: bin/colorize_terminal.sh
    dst: ~/bin/colorize_terminal.sh
    link: link
    chmod: "775"
  f_delta.sh:
    src: bin/delta.sh
    dst: ~/bin/delta.sh
    link: link
    chmod: "775"
profiles:
  armonge-laptop:
    dotfiles:
      - f_bashrc
      - f_init.vim
      - f_installer.sh
      - f_gitconfig
      - f_asus_zenbook3_deluxe_auo_b140han03_8.icm
      - f_ctags
      - f_bash_profile
      - f_chromium-flags.conf
      - f_typescript.snippets
      - f_bash_aliases
      - f_attributes
      - f_deps.edn
      - f_coc-settings.json
      - f_config.toml
      - f_ideavimrc
      - f_dircolors
      - f_ftplugin_audio.vim
      - f_video.vim
      - f_audio.vim
      - f_colorize_terminal.sh
      - f_delta.sh
