actions:
  post:
    dein: nvim --cmd ':call dein#recache_runtimepath()'
    dein_install: if [ ! -f "$HOME/.dein.cache/repos/github.com/Shougo/dein.vim" ]; then cd ~/.config/nvim/ && ./installer.sh ~/.dein.cache/ fi
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: link
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_asus_zenbook3_deluxe_auo_b140han03_8.icm:
    dst: ~/.local/share/icc/Asus_Zenbook3_Deluxe_AUO_B140HAN03_8.icm
    link: link
    src: local/share/icc/Asus_Zenbook3_Deluxe_AUO_B140HAN03_8.icm
  f_bash_aliases:
    dst: ~/.bash_aliases
    link: link
    src: bash_aliases
  f_bash_profile:
    dst: ~/.bash_profile
    link: link
    src: bash_profile
  f_bashrc:
    dst: ~/.bashrc
    link: link
    src: bashrc
  f_chromium-flags.conf:
    dst: ~/.config/chromium-flags.conf
    link: link
    src: config/chromium-flags.conf
  f_ctags:
    dst: ~/.ctags
    link: link
    src: ctags
  f_gitconfig:
    dst: ~/.gitconfig
    link: link
    src: gitconfig
  f_init.vim:
    actions:
    - dein
    dst: ~/.config/nvim/init.vim
    link: link
    src: config/nvim/init.vim
  f_installer.sh:
    actions:
    - dein_install
    dst: ~/.config/nvim/installer.sh
    link: link
    src: config/nvim/installer.sh
  f_typescript.snippets:
    dst: ~/.config/nvim/UltiSnips/typescript.snippets
    link: link
    src: config/nvim/UltiSnips/typescript.snippets
profiles:
  armonge-laptop:
    dotfiles:
    - f_bashrc
    - f_init.vim
    - f_installer.sh
    - f_gitconfig
    - f_asus_zenbook3_deluxe_auo_b140han03_8.icm
    - f_ctags
    - f_bash_profile
    - f_chromium-flags.conf
    - f_typescript.snippets
    - f_bash_aliases
  
  armonge-vui-laptop:
    dotfiles:
    - f_bashrc
    - f_init.vim
    - f_installer.sh
    - f_gitconfig
    - f_asus_zenbook3_deluxe_auo_b140han03_8.icm
    - f_ctags
    - f_bash_profile
    - f_chromium-flags.conf
    - f_typescript.snippets
    - f_bash_aliases
