config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: link
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
  minversion: 1.15.0
dotfiles:
  f_bash_aliases:
    dst: ~/.bash_aliases
    link: absolute
    src: bash_aliases
  f_bash_profile:
    dst: ~/.bash_profile
    link: absolute
    src: bash_profile
  f_bashrc:
    dst: ~/.bashrc
    link: absolute
    src: bashrc
    chmod: '644'
  f_chromium-flags.conf:
    dst: ~/.config/chromium-flags.conf
    link: absolute
    src: config/chromium-flags.conf
  f_ctags:
    dst: ~/.ctags
    link: absolute
    src: ctags
  f_gitconfig:
    dst: ~/.gitconfig
    link: absolute
    src: gitconfig
  f_init.lua:
    dst: ~/.config/nvim/init.lua
    link: absolute
    src: config/nvim/init.lua
  f_attributes:
    src: config/git/attributes
    dst: ~/.config/git/attributes
    link: absolute
  f_config.toml:
    src: config/pypoetry/config.toml
    dst: ~/.config/pypoetry/config.toml
    link: absolute
  f_ideavimrc:
    src: ideavimrc
    dst: ~/.ideavimrc
    link: absolute
  f_delta.sh:
    src: bin/delta.sh
    dst: ~/bin/delta.sh
    link: absolute
    chmod: '775'
  f_rifle.conf:
    src: config/ranger/rifle.conf
    dst: ~/.config/ranger/rifle.conf
    link: absolute
    chmod: '644'
  f_version:
    src: pyenv/version
    dst: ~/.pyenv/version
    link: absolute
  f_scope.sh:
    src: config/ranger/scope.sh
    dst: ~/.config/ranger/scope.sh
    link: absolute
    chmod: '755'
  f_inputrc:
    src: inputrc
    dst: ~/.inputrc
    link: absolute
  f_mirror.sh:
    src: local/bin/mirror.sh
    dst: ~/.local/bin/mirror.sh
    link: absolute
    chmod: '775'
  f_dsq:
    src: local/bin/dsq
    dst: ~/.local/bin/dsq
    link: absolute
    chmod: '755'
  f_ignore:
    src: config/nvim/.ignore
    dst: ~/.config/nvim/.ignore
    link: absolute
  f_armonge_init.lua:
    src: config/nvim/lua/armonge/init.lua
    dst: ~/.config/nvim/lua/armonge/init.lua
    link: absolute
  f_defaults.lua:
    src: config/nvim/lua/armonge/defaults.lua
    dst: ~/.config/nvim/lua/armonge/defaults.lua
    link: absolute
  f_environment.lua:
    src: config/nvim/lua/armonge/environment.lua
    dst: ~/.config/nvim/lua/armonge/environment.lua
    link: absolute
  f_filetypes.lua:
    src: config/nvim/lua/armonge/filetypes.lua
    dst: ~/.config/nvim/lua/armonge/filetypes.lua
    link: absolute
  f_plugins.lua:
    src: config/nvim/lua/armonge/plugins.lua
    dst: ~/.config/nvim/lua/armonge/plugins.lua
    link: absolute
  f_theme.lua:
    src: config/nvim/lua/armonge/theme.lua
    dst: ~/.config/nvim/lua/armonge/theme.lua
    link: absolute
  f_python-version:
    src: config/nvim/.python-version
    dst: ~/.config/nvim/.python-version
    link: absolute
  f_git_ignore:
    src: config/git/ignore
    dst: ~/.config/git/ignore
    link: absolute
  f_treesitter.lua:
    src: config/nvim/lua/armonge/treesitter.lua
    dst: ~/.config/nvim/lua/armonge/treesitter.lua
    link: absolute
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
    link: absolute
  f_00-logging.py:
    src: ipython/profile_default/startup/00-logging.py
    dst: ~/.ipython/profile_default/startup/00-logging.py
    link: absolute
  f_rc.conf:
    src: config/ranger/rc.conf
    dst: ~/.config/ranger/rc.conf
    link: absolute
  f_rgignore:
    src: rgignore
    dst: ~/.rgignore
    link: absolute
  f_direnv_direnvrc:
    src: config/direnv/direnvrc
    dst: ~/.config/direnv/direnvrc
    link: absolute
  f_direnv.toml:
    src: config/direnv/direnv.toml
    dst: ~/.config/direnv/direnv.toml
    link: absolute
  f_tokyonight_night.tmtheme:
    src: config/bat/themes/tokyonight_night.tmTheme
    dst: ~/.config/bat/themes/tokyonight_night.tmTheme
    link: absolute
  f_lsp.lua:
    src: config/nvim/lua/armonge/lsp.lua
    dst: ~/.config/nvim/lua/armonge/lsp.lua
    link: absolute
  f_wezterm.lua:
    src: config/wezterm/wezterm.lua
    dst: ~/.config/wezterm/wezterm.lua
    link: absolute
  f_editorconfig:
    src: config/nvim/.editorconfig
    dst: ~/.config/nvim/.editorconfig
    link: absolute
  f_motions.lua:
    src: config/nvim/lua/armonge/motions.lua
    dst: ~/.config/nvim/lua/armonge/motions.lua
    link: absolute
  f_lazy-lock.json:
    src: config/nvim/lazy-lock.json
    dst: ~/.config/nvim/lazy-lock.json
    link: absolute
  f_editor.lua:
    src: config/nvim/editor.lua
    dst: ~/.config/nvim/editor.lua
    link: absolute
  f_mappings.lua:
    src: config/nvim/lua/armonge/mappings.lua
    dst: ~/.config/nvim/lua/armonge/mappings.lua
    link: absolute
  f_clojure.lua:
    src: config/nvim/lua/armonge/clojure.lua
    dst: ~/.config/nvim/lua/armonge/clojure.lua
    link: absolute
  f_oil.lua:
    src: config/nvim/lua/armonge/oil.lua
    dst: ~/.config/nvim/lua/armonge/oil.lua
    link: absolute
  f_snacks.lua:
    src: config/nvim/lua/armonge/snacks.lua
    dst: ~/.config/nvim/lua/armonge/snacks.lua
    link: absolute
  f_blink.lua:
    src: config/nvim/lua/armonge/blink.lua
    dst: ~/.config/nvim/lua/armonge/blink.lua
    link: absolute
  f_mini.lua:
    src: config/nvim/lua/armonge/mini.lua
    dst: ~/.config/nvim/lua/armonge/mini.lua
    link: absolute
  f_en.utf-8.add:
    src: config/nvim/spell/en.utf-8.add
    dst: ~/.config/nvim/spell/en.utf-8.add
    link: absolute
  d_wezterm:
    src: config/wezterm
    dst: ~/.config/wezterm
    link: absolute
  d_direnv:
    src: config/direnv
    dst: ~/.config/direnv
    link: absolute
profiles:
  armonge-laptop:
    dotfiles:
    - f_bashrc
    - f_gitconfig
    - f_ctags
    - f_bash_profile
    - f_chromium-flags.conf
    - f_bash_aliases
    - f_attributes
    - f_config.toml
    - f_ideavimrc
    - f_delta.sh
    - f_rifle.conf
    - f_version
    - f_scope.sh
    - f_inputrc
    - f_mirror.sh
    - f_dsq
    - f_init.lua
    - f_ignore
    - f_armonge_init.lua
    - f_defaults.lua
    - f_environment.lua
    - f_filetypes.lua
    - f_plugins.lua
    - f_theme.lua
    - f_python-version
    - f_git_ignore
    - f_treesitter.lua
    - f_starship.toml
    - f_00-logging.py
    - f_rc.conf
    - f_rgignore
    - f_direnv_direnvrc
    - f_direnv.toml
    - f_tokyonight_night.tmtheme
    - f_lsp.lua
    - f_wezterm.lua
    - f_editorconfig
    - f_motions.lua
    - f_lazy-lock.json
    - f_editor.lua
    - f_mappings.lua
    - f_clojure.lua
    - f_oil.lua
    - f_snacks.lua
    - f_blink.lua
    - f_mini.lua
    - f_en.utf-8.add
    - d_wezterm
    - d_direnv
