actions:
  post:
    dein: vim --cmd ':call dein#recache_runtimepath()'
    dein_install: cd ~/.cofig/nvim/ && ./installer.sh
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_by_default: true
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_asus_zenbook3_deluxe_auo_b140han03_8.icm:
    dst: ~/.local/share/icc/Asus_Zenbook3_Deluxe_AUO_B140HAN03_8.icm
    link: true
    src: local/share/icc/Asus_Zenbook3_Deluxe_AUO_B140HAN03_8.icm
  f_bash_profile:
    dst: ~/.bash_profile
    link: true
    src: bash_profile
  f_bashrc:
    dst: ~/.bashrc
    link: true
    src: bashrc
  f_ctags:
    dst: ~/.ctags
    link: true
    src: ctags
  f_gitconfig:
    dst: ~/.gitconfig
    link: true
    src: gitconfig
  f_init.vim:
    actions:
    - dein
    dst: ~/.config/nvim/init.vim
    link: true
    src: config/nvim/init.vim
  f_installer.sh:
    actions:
    - dein_install
    dst: ~/.config/nvim/installer.sh
    link: true
    src: config/nvim/installer.sh
profiles:
  armonge-laptop:
    dotfiles:
    - f_bashrc
    - f_init.vim
    - f_installer.sh
    - f_gitconfig
    - f_asus_zenbook3_deluxe_auo_b140han03_8.icm
    - f_ctags
    - f_bash_profile
