config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: link
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
  minversion: 1.14.0
actions:
  pre:
    install_deps: ./scripts/install-deps.sh
  post:
    update_cache: bat cache --build

dotfiles:
  f_bash_aliases:
    dst: ~/.bash_aliases
    link: absolute
    src: bash_aliases
  f_bash_profile:
    dst: ~/.bash_profile
    link: absolute
    src: bash_profile
  f_bashrc:
    dst: ~/.bashrc
    link: absolute
    src: bashrc
    chmod: '644'
  f_chromium-flags.conf:
    dst: ~/.config/chromium-flags.conf
    link: absolute
    src: config/chromium-flags.conf
  f_ctags:
    dst: ~/.ctags
    link: absolute
    src: ctags
  f_gitconfig:
    dst: ~/.gitconfig
    link: absolute
    src: gitconfig
  f_init.lua:
    dst: ~/.config/nvim/init.lua
    link: absolute
    src: config/nvim/init.lua
    actions:
    - install_deps
  f_attributes:
    src: config/git/attributes
    dst: ~/.config/git/attributes
    link: absolute
  f_deps.edn:
    src: clojure/deps.edn
    dst: ~/.clojure/deps.edn
    link: absolute
  f_config.toml:
    src: config/pypoetry/config.toml
    dst: ~/.config/pypoetry/config.toml
    link: absolute
  f_ideavimrc:
    src: ideavimrc
    dst: ~/.ideavimrc
    link: absolute
  f_delta.sh:
    src: bin/delta.sh
    dst: ~/bin/delta.sh
    link: absolute
    chmod: '775'
  f_rifle.conf:
    src: config/ranger/rifle.conf
    dst: ~/.config/ranger/rifle.conf
    link: absolute
    chmod: '644'
  f_version:
    src: pyenv/version
    dst: ~/.pyenv/version
    link: absolute
  f_clojure_deps.edn:
    src: config/clojure/deps.edn
    dst: ~/.config/clojure/deps.edn
    link: absolute
  f_rebel_readline.edn:
    src: config/clojure/rebel_readline.edn
    dst: ~/.config/clojure/rebel_readline.edn
    link: absolute
  f_practicalli-custom-dictionary.txt:
    src: config/clojure/.cspell/practicalli-custom-dictionary.txt
    dst: ~/.config/clojure/.cspell/practicalli-custom-dictionary.txt
    link: absolute
  f_cspell.json:
    src: config/clojure/.cspell.json
    dst: ~/.config/clojure/.cspell.json
    link: absolute
  f_clojure-lsp:
    src: local/bin/clojure-lsp
    dst: ~/.local/bin/clojure-lsp
    link: absolute
    chmod: '755'
  f_scope.sh:
    src: config/ranger/scope.sh
    dst: ~/.config/ranger/scope.sh
    link: absolute
    chmod: '755'
  f_inputrc:
    src: inputrc
    dst: ~/.inputrc
    link: absolute
  f_mirror.sh:
    src: local/bin/mirror.sh
    dst: ~/.local/bin/mirror.sh
    link: absolute
    chmod: '775'
  f_dsq:
    src: local/bin/dsq
    dst: ~/.local/bin/dsq
    link: absolute
    chmod: '755'
  f_ignore:
    src: config/nvim/.ignore
    dst: ~/.config/nvim/.ignore
    link: absolute
  f_armonge_init.lua:
    src: config/nvim/lua/armonge/init.lua
    dst: ~/.config/nvim/lua/armonge/init.lua
    link: absolute
  f_defaults.lua:
    src: config/nvim/lua/armonge/defaults.lua
    dst: ~/.config/nvim/lua/armonge/defaults.lua
    link: absolute
  f_environment.lua:
    src: config/nvim/lua/armonge/environment.lua
    dst: ~/.config/nvim/lua/armonge/environment.lua
    link: absolute
  f_filebrowser.lua:
    src: config/nvim/lua/armonge/filebrowser.lua
    dst: ~/.config/nvim/lua/armonge/filebrowser.lua
    link: absolute
  f_filetypes.lua:
    src: config/nvim/lua/armonge/filetypes.lua
    dst: ~/.config/nvim/lua/armonge/filetypes.lua
    link: absolute
  f_plugins.lua:
    src: config/nvim/lua/armonge/plugins.lua
    dst: ~/.config/nvim/lua/armonge/plugins.lua
    link: absolute
  f_theme.lua:
    src: config/nvim/lua/armonge/theme.lua
    dst: ~/.config/nvim/lua/armonge/theme.lua
    link: absolute
  f_python-version:
    src: config/nvim/.python-version
    dst: ~/.config/nvim/.python-version
    link: absolute
  f_git_ignore:
    src: config/git/ignore
    dst: ~/.config/git/ignore
    link: absolute
  f_treesitter.lua:
    src: config/nvim/lua/armonge/treesitter.lua
    dst: ~/.config/nvim/lua/armonge/treesitter.lua
    link: absolute
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
    link: absolute
  f_telescope.lua:
    src: config/nvim/lua/armonge/telescope.lua
    dst: ~/.config/nvim/lua/armonge/telescope.lua
    link: absolute
  f_01-nord.py:
    src: ipython/profile_default/startup/01-nord.py
    dst: ~/.ipython/profile_default/startup/01-nord.py
    link: absolute
  f_00-logging.py:
    src: ipython/profile_default/startup/00-logging.py
    dst: ~/.ipython/profile_default/startup/00-logging.py
    link: absolute
  f_rc.conf:
    src: config/ranger/rc.conf
    dst: ~/.config/ranger/rc.conf
    link: absolute
  f_rgignore:
    src: rgignore
    dst: ~/.rgignore
    link: absolute
  f_direnv_direnvrc:
    src: config/direnv/direnvrc
    dst: ~/.config/direnv/direnvrc
    link: absolute
  f_direnv.toml:
    src: config/direnv/direnv.toml
    dst: ~/.config/direnv/direnv.toml
    link: absolute
  f_tokyonight_night.tmtheme:
    src: config/bat/themes/tokyonight_night.tmTheme
    dst: ~/.config/bat/themes/tokyonight_night.tmTheme
    link: absolute
    actions:
      - update_cache
  f_lsp.lua:
    src: config/nvim/lua/armonge/lsp.lua
    dst: ~/.config/nvim/lua/armonge/lsp.lua
    link: absolute
  f_completion.lua:
    src: config/nvim/lua/armonge/completion.lua
    dst: ~/.config/nvim/lua/armonge/completion.lua
    link: absolute
  f_wezterm.lua:
    src: config/wezterm/wezterm.lua
    dst: ~/.config/wezterm/wezterm.lua
    link: absolute
profiles:
  armonge-laptop:
    dotfiles:
    - f_bashrc
    - f_gitconfig
    - f_ctags
    - f_bash_profile
    - f_chromium-flags.conf
    - f_bash_aliases
    - f_attributes
    - f_deps.edn
    - f_config.toml
    - f_ideavimrc
    - f_delta.sh
    - f_rifle.conf
    - f_version
    - f_clojure_deps.edn
    - f_rebel_readline.edn
    - f_practicalli-custom-dictionary.txt
    - f_cspell.json
    - f_clojure-lsp
    - f_scope.sh
    - f_inputrc
    - f_mirror.sh
    - f_dsq
    - f_init.lua
    - f_ignore
    - f_armonge_init.lua
    - f_defaults.lua
    - f_environment.lua
    - f_filebrowser.lua
    - f_filetypes.lua
    - f_plugins.lua
    - f_theme.lua
    - f_python-version
    - f_git_ignore
    - f_treesitter.lua
    - f_starship.toml
    - f_telescope.lua
    - f_01-nord.py
    - f_00-logging.py
    - f_rc.conf
    - f_rgignore
    - f_direnv_direnvrc
    - f_direnv.toml
    - f_tokyonight_night.tmtheme
    - f_lsp.lua
    - f_completion.lua
    - f_wezterm.lua
