config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: link
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
  minversion: 1.10.0
actions:
  dein_init: ~/.config/nvim/installer.sh ~/.dein.cache
  pre:
    install_deps: ./scripts/install-deps.sh
dotfiles:
  f_asus_zenbook3_deluxe_auo_b140han03_8.icm:
    dst: ~/.local/share/icc/Asus_Zenbook3_Deluxe_AUO_B140HAN03_8.icm
    link: absolute
    src: local/share/icc/Asus_Zenbook3_Deluxe_AUO_B140HAN03_8.icm
  f_bash_aliases:
    dst: ~/.bash_aliases
    link: absolute
    src: bash_aliases
  f_bash_profile:
    dst: ~/.bash_profile
    link: absolute
    src: bash_profile
  f_bashrc:
    dst: ~/.bashrc
    link: absolute
    src: bashrc
    chmod: '644'
  f_chromium-flags.conf:
    dst: ~/.config/chromium-flags.conf
    link: absolute
    src: config/chromium-flags.conf
  f_ctags:
    dst: ~/.ctags
    link: absolute
    src: ctags
  f_gitconfig:
    dst: ~/.gitconfig
    link: absolute
    src: gitconfig
  f_init.vim:
    dst: ~/.config/nvim/init.vim
    link: absolute
    src: config/nvim/init.vim
    actions:
    - install_deps
  f_installer.sh:
    dst: ~/.config/nvim/installer.sh
    link: absolute
    src: config/nvim/installer.sh
    actions:
    - dein_init
  f_typescript.snippets:
    dst: ~/.config/nvim/UltiSnips/typescript.snippets
    link: absolute
    src: config/nvim/UltiSnips/typescript.snippets
  f_attributes:
    src: config/git/attributes
    dst: ~/.config/git/attributes
    link: absolute
  f_deps.edn:
    src: clojure/deps.edn
    dst: ~/.clojure/deps.edn
    link: absolute
  f_coc-settings.json:
    src: config/nvim/coc-settings.json
    dst: ~/.config/nvim/coc-settings.json
    link: absolute
  f_config.toml:
    src: config/pypoetry/config.toml
    dst: ~/.config/pypoetry/config.toml
    link: absolute
  f_ideavimrc:
    src: ideavimrc
    dst: ~/.ideavimrc
    link: absolute
  f_audio.vim:
    src: config/nvim/ftdetect/audio.vim
    dst: ~/.config/nvim/ftdetect/audio.vim
    link: absolute
  f_video.vim:
    src: config/nvim/ftdetect/video.vim
    dst: ~/.config/nvim/ftdetect/video.vim
    link: absolute
  f_ftplugin_audio.vim:
    src: config/nvim/after/ftplugin/audio.vim
    dst: ~/.config/nvim/after/ftplugin/audio.vim
    link: absolute
  f_ftplugin_video.vim:
    src: config/nvim/after/ftplugin/video.vim
    dst: ~/.config/nvim/after/ftplugin/video.vim
    link: absolute
  f_delta.sh:
    src: bin/delta.sh
    dst: ~/bin/delta.sh
    link: absolute
    chmod: '775'
  f_rifle.conf:
    src: config/ranger/rifle.conf
    dst: ~/.config/ranger/rifle.conf
    link: absolute
    chmod: '644'
  f_version:
    src: pyenv/version
    dst: ~/.pyenv/version
    link: absolute
  f_default:
    src: nvm/alias/default
    dst: ~/.nvm/alias/default
    link: absolute
  f_*:
    src: nvm/alias/lts/*
    dst: ~/.nvm/alias/lts/*
    link: absolute
  f_shfmt:
    src: local/bin/shfmt
    dst: ~/.local/bin/shfmt
    link: absolute
    chmod: '755'
  f_clojure_deps.edn:
    src: config/clojure/deps.edn
    dst: ~/.config/clojure/deps.edn
    link: absolute
  f_rebel_readline.edn:
    src: config/clojure/rebel_readline.edn
    dst: ~/.config/clojure/rebel_readline.edn
    link: absolute
  f_practicalli-custom-dictionary.txt:
    src: config/clojure/.cspell/practicalli-custom-dictionary.txt
    dst: ~/.config/clojure/.cspell/practicalli-custom-dictionary.txt
    link: absolute
  f_cspell.json:
    src: config/clojure/.cspell.json
    dst: ~/.config/clojure/.cspell.json
    link: absolute
  f_clojure-lsp:
    src: local/bin/clojure-lsp
    dst: ~/.local/bin/clojure-lsp
    link: absolute
    chmod: '755'
  f_scope.sh:
    src: config/ranger/scope.sh
    dst: ~/.config/ranger/scope.sh
    link: absolute
    chmod: '755'
  f_inputrc:
    src: inputrc
    dst: ~/.inputrc
    link: absolute
  f_giteditor.sh:
    src: local/bin/giteditor.sh
    dst: ~/.local/bin/giteditor.sh
    link: absolute
    chmod: '775'
profiles:
  armonge-laptop:
    dotfiles:
    - f_bashrc
    - f_init.vim
    - f_installer.sh
    - f_gitconfig
    - f_asus_zenbook3_deluxe_auo_b140han03_8.icm
    - f_ctags
    - f_bash_profile
    - f_chromium-flags.conf
    - f_typescript.snippets
    - f_bash_aliases
    - f_attributes
    - f_deps.edn
    - f_coc-settings.json
    - f_config.toml
    - f_ideavimrc
    - f_ftplugin_audio.vim
    - f_video.vim
    - f_audio.vim
    - f_delta.sh
    - f_rifle.conf
    - f_version
    - f_default
    - f_*
    - f_shfmt
    - f_clojure_deps.edn
    - f_rebel_readline.edn
    - f_practicalli-custom-dictionary.txt
    - f_cspell.json
    - f_clojure-lsp
    - f_scope.sh
    - f_inputrc
    - f_giteditor.sh
