# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

[gcloud]
disabled = true

[fossil_branch]
disabled = true

[hostname]
ssh_only = true
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
disabled = false

[git_metrics]
disabled = false
